#!/usr/bin/env python3
"""Emit latex/numbers.tex — every corpus figure the paper quotes, as a LaTeX macro.

The methodology section of a systematic review is full of numbers that change every time
the harvest runs. Typing them into the manuscript guarantees they go stale and disagree
with the repository. This writes them as macros instead, so `main.tex` says
\\CorpusDedup and the number is whatever the last harvest actually produced.

  python3 tools/make_latex.py        # -> latex/numbers.tex
"""
import csv, json, os, collections

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)                    # tools/ -> repository root
DATA = os.path.join(ROOT, "data")
csv.field_size_limit(10_000_000)
p = lambda *a: os.path.join(DATA, *a)

def load(name, default=None):
    try:
        return json.load(open(p(name), encoding="utf-8"))
    except (FileNotFoundError, ValueError):
        return default if default is not None else {}

rep, audit, read = load("harvest_report.json"), load("recall_audit.json"), load("reading_list.json")
rows = list(csv.DictReader(open(p("corpus_screening.csv"), encoding="utf-8")))
dec = collections.Counter(r["decision"] for r in rows)
codes = collections.Counter(r["reason_code"] for r in rows if r["decision"] == "exclude")

SRC_LABEL = {"openalex": "OpenAlex", "crossref": "Crossref", "s2": "SemanticScholar",
             "arxiv": "arXiv", "dblp": "DBLP", "openreview": "OpenReview",
             "ieee": "IEEEXplore", "scopus": "Scopus", "wos": "WoS"}

DIGIT = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
         "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}

def macro_name(s):
    """LaTeX control words are letters only: EC1 has to become ECOne."""
    return "".join(DIGIT.get(c, c) for c in s if c.isalnum())


def tex_int(n):
    """IEEE style: a thin space every three digits, so 11244 reads as 11 244."""
    s = f"{int(n or 0):,}".replace(",", r"\,")
    return s

macros = {
    "CorpusRaw": tex_int(rep.get("raw_records")),
    "CorpusDedup": tex_int(rep.get("after_dedup")),
    "CorpusDupes": tex_int(rep.get("duplicates_removed")),
    "CorpusMultiSource": tex_int(rep.get("multi_source")),
    "CorpusPreprint": tex_int(rep.get("preprint_only")),
    "HarvestDate": rep.get("retrieved", ""),
    "HarvestWindow": rep.get("window", ""),
    "FailedRequests": tex_int(rep.get("failed_requests")),
    "SeedTotal": tex_int(audit.get("seeds")),
    "SeedFound": tex_int(audit.get("found")),
    "RecallAll": (audit.get("recall_all") or "").replace("/", "/"),
    "RecallWindow": (audit.get("recall_in_window") or ""),
    "ScrInclude": tex_int(dec.get("include")),
    "ScrCheck": tex_int(dec.get("check")),
    "ScrSurvey": tex_int(dec.get("survey")),
    "ScrExclude": tex_int(dec.get("exclude")),
    "ReadTotal": tex_int(len(read.get("rows") or [])),
    "ReadPool": tex_int(read.get("pool")),
    "ReadFrom": str(read.get("from_year", "")),
    "ReadTo": str(read.get("to_year", "")),
}
for code, n in codes.items():
    if code:
        macros[macro_name("Scr" + code)] = tex_int(n)
for src, n in (rep.get("per_source") or {}).items():
    macros[macro_name("Src" + SRC_LABEL.get(src, src.title()))] = tex_int(n)
for qs, n in (rep.get("per_set_after_dedup") or {}).items():
    macros[macro_name("Set" + qs.title())] = tex_int(n)
for qs, n in (rep.get("per_set") or {}).items():
    macros[macro_name("SetRaw" + qs.title())] = tex_int(n)

os.makedirs(os.path.join(ROOT, "latex"), exist_ok=True)
with open(os.path.join(ROOT, "latex", "numbers.tex"), "w", encoding="utf-8") as f:
    f.write("% Generated by make_latex.py — do not edit. Re-run ./refresh.sh after a harvest.\n")
    f.write(f"% corpus retrieved {macros['HarvestDate']}\n")
    for k in sorted(macros):
        f.write(f"\\newcommand{{\\{macro_name(k)}}}{{{macros[k]}}}\n")
print(f"latex/numbers.tex  {len(macros)} macros  "
      f"(corpus {macros['CorpusDedup']}, recall {macros['RecallWindow']})")
