#!/usr/bin/env python3
"""Build latex/refs.bib from the reading list, using each paper's own record.

BibTeX is fetched from doi.org by content negotiation, so the entry is the
publisher's own: full author list, correct venue, correct pages. The corpus CSV
cannot supply this -- it truncates authors at four -- so nothing here is
reconstructed from our metadata.

arXiv-only papers are fetched through their DataCite DOI (10.48550/arXiv.ID).
Anything with neither a DOI nor an arXiv id is reported, not invented.

  python3 tools/make_bib.py              # -> latex/refs.bib
  python3 tools/make_bib.py --force      # refetch entries already cached

Citation keys are rewritten to a stable short form (firstauthor+year+word) so
they survive a refetch, and the reading-list rank is kept as a comment.
"""
import csv, os, re, sys, time, urllib.error, urllib.parse, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)                    # tools/ -> repository root
DATA = os.path.join(ROOT, "data")
p = lambda *a: os.path.join(DATA, *a)
csv.field_size_limit(10_000_000)
try:
    import certifi
    os.environ.setdefault("SSL_CERT_FILE", certifi.where())
except ImportError:
    pass

CACHE = os.path.join(ROOT, "latex", ".bibcache")
UA = {"User-Agent": "gtu-vln-survey/1.0 (academic literature review)",
      "Accept": "application/x-bibtex; charset=utf-8"}

def fetch(doi):
    url = "https://doi.org/" + urllib.parse.quote(doi, safe="/:")
    for attempt in range(3):
        try:
            with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=45) as r:
                return r.read().decode("utf-8", "replace").strip()
        except urllib.error.HTTPError as e:
            if e.code in (404, 406): return ""
            time.sleep(4 * (attempt + 1))
        except Exception:
            time.sleep(4 * (attempt + 1))
    return ""

MONTHS = {m: m[:3].lower() for m in
          ("January February March April May June July August September "
           "October November December").split()}

def fix_months(entry):
    """Crossref emits `month=May`; BibTeX only knows the macros jan..dec."""
    return re.sub(r"(month\s*=\s*)\{?([A-Z][a-z]+)\}?",
                  lambda m: m.group(1) + MONTHS.get(m.group(2), m.group(2).lower()[:3]),
                  entry)


def key_for(entry, fallback):
    m = re.search(r"@\w+\{([^,]+),", entry)
    return m.group(1).strip() if m else fallback

def short_key(entry, row):
    # Crossref returns one long line, DataCite a pretty-printed block: match both
    au = re.search(r"author\s*=\s*\{(.*?)\}\s*,", entry, re.S | re.I)
    first = ""
    if au:
        first = re.split(r"\s+and\s+", au.group(1).strip())[0]
        first = first.split(",")[0] if "," in first else first.split()[-1]
        first = re.sub(r"[^A-Za-z]", "", first).lower()
    word = next((w.lower() for w in re.findall(r"[A-Za-z]{4,}", row["title"] or "")), "work")
    return f"{first or 'anon'}{row.get('year','')}{word}"

def main():
    force = "--force" in sys.argv
    os.makedirs(CACHE, exist_ok=True)
    rows = list(csv.DictReader(open(p("reading_list.csv"), encoding="utf-8-sig")))
    out, missing, cached, fetched = [], [], 0, 0
    used = {}

    for r in rows:
        doi = (r.get("doi") or "").strip()
        arx = (r.get("arxiv") or "").strip()
        ident = doi or (f"10.48550/arXiv.{arx}" if arx else "")
        if not ident:
            missing.append(r); continue
        cf = os.path.join(CACHE, re.sub(r"[^A-Za-z0-9._-]", "_", ident) + ".bib")
        if os.path.exists(cf) and not force:
            entry = open(cf, encoding="utf-8").read(); cached += 1
        else:
            entry = fetch(ident); fetched += 1
            if entry: open(cf, "w", encoding="utf-8").write(entry)
            time.sleep(0.7)
        if not entry:
            missing.append(r); continue
        key = short_key(entry, r)
        # two papers by the same first author, year and leading title word would
        # otherwise emit the same key and BibTeX would drop the second silently
        if key in used:
            used[key] += 1
            key = f"{key}{chr(ord('a') + used[key] - 1)}"
        else:
            used[key] = 1
        entry = fix_months(entry.replace(key_for(entry, "x"), key, 1))
        out.append(f"% [{r['rank']}] {r['tier']}\n{entry}\n")

    os.makedirs(os.path.join(ROOT, "latex"), exist_ok=True)
    with open(os.path.join(ROOT, "latex", "refs.bib"), "w", encoding="utf-8") as f:
        f.write("% Generated by make_bib.py from data/reading_list.csv.\n"
                "% Entries come from doi.org content negotiation -- the publisher's own record.\n"
                "% Re-run after the reading list changes; cached in latex/.bibcache.\n\n")
        f.write("\n".join(out))
    dupes = sum(v - 1 for v in used.values() if v > 1)
    print(f"latex/refs.bib  {len(out)} entries  ({cached} cached, {fetched} fetched"
          + (f", {dupes} key collisions suffixed" if dupes else "") + ")")
    if missing:
        print(f"\n{len(missing)} without a resolvable DOI -- add these by hand:")
        for r in missing[:12]:
            print(f"  [{r['rank']}] {r['title'][:66]}")

if __name__ == "__main__":
    main()
